### PR TITLE
Moved most variables in packet_encode class into own class parameters

### PR DESCRIPTION
**Pull request by dn1s**
Tackeled this with the pr "TODO: Instead of passing all args in via kwargs, should actually explicitly set each attribute"

### CODE REVIEW

**Comment by dn1s** [comment]
Forgot to fix test :(
Gonna do that now.

**Comment by dn1s** [comment]
@rucarrol can you check which values I should be testing for the failed tests?
They didn't get executed before since the tests where named the same and only the last one with the name got exectuted.

**Comment by rucarrol** [comment]
Hey @dn1s ! First - thank you for taking some time to take a go at this.

First - over the weekend, we implemented python black for code quality. 

You can see how to use it [here](https://pypi.org/project/black/) (tl;dr: `pip install black && black .`). This should pass the linting part of the build that's failing.

Next, testing. Let me review this a bit and see what's going on!

**Comment by rucarrol** [comment]
I see that there are two failures right now.

`test_encode_ipv4_l4_proto_local_ip` fails as it's picking the dynamic IP of the local box. I'll work on fixing this.

`test_encode_ipv4_l4_proto_fixed_checksum` is failing as checksum is calculated to be 0. I'll also work on fix this this.

**Comment by dn1s** [comment]
So I did run ```black .``` now and commented both checks out for the time being.

**Comment by dn1s** [comment]
Obiously I did it in the wrong order xD

**Review by awlx — APPROVED** [review]
LGTM

**Comment by rucarrol** [comment]
Thank you @dn1s, for this PR. It's committed now.

**Pull request merged**
